### ISSUE TITLE
[Swag] Pins

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#104]
Option to get enamel pins as swag. Saw these at donut.js

My thought is that this would make a good limited run of swag for a special event. 

Pin Pros Plus: https://www.pinprosplus.com/--

**Comment by lindaleebumblebee** [comment]
I like this idea to gamify the contributor experience. So, we could have 2-3 different designs for 'rockstar contributors' that make a certain amount of Gatsby contributions. Limited to certain level of contributors only!

**Comment by jlengstorf** [comment]
As an initial experiment, we've ordered one pin. Should be available soon!

**Comment by jlengstorf** [comment]
Pins are in the store!
