### ISSUE TITLE
[Swag] Gatsby Sunglasses

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#105]
Swag idea: Black sunglasses with Gatsby purple on the side. Could be a good option for a limited run of swag.

@shannonbux: This is largely just a ploy to get a picture of Watson wearing sunglasses. Just thought you should know. :)

**Comment by shannonbux** [comment]
@marisamorby hahaha Watson can probably be persuaded to do that for a treat
;D

**Comment by jlengstorf** [comment]
Superseded by #224

**Comment by Mukeshgaur12** [comment]
Swag idea: Black sunglasses with Gatsby purple on the side. Could be a good option for a limited run of swag.

**Comment by Mukeshgaur12** [comment]
#388 WE can add more attarctive ideas like cutting theedges of the web page to white or green to spreading aware ness through messages
