### ISSUE TITLE
Stuck on callback page

### ISSUE THREAD

**Issue by merelinguist** [gatsbyjs/store.gatsbyjs.org#106]
Recently made my first Gatsby PR and trying to use the login button, but I don’t get redirected past the callback page.

**Comment by jlengstorf** [comment]
Hey, Dylan! Are you seeing any errors in the console? What browser are you using? We've seen some weirdness with Safari (#93 should fix this), so if that's what you're using maybe give another browser a shot until we have the chance to patch that up.

Thanks!

**Comment by merelinguist** [comment]
Hey. I’m using Firefox on iOS (also tried Safari). I actually can’t get to a desktop  until next week, but I’ll try again there and update you :). Thanks!

**Comment by jlengstorf** [comment]
Sorry about that! I'll see if I can clear some time to fix the Safari issue sooner. (I think it has to do with the localStorage usage, which I _think_ is weird on iOS.)

**Comment by merelinguist** [comment]
Awesome 😎!

**Comment by stlk** [comment]
I stumbled upon this issue too on Safari 11.1.2 (13605.3.8). It works fine on Firefox 61.0.1. Warning gets printed into console:
```
The resource https://store.gatsbyjs.org/static/d/696/path---callback-01-b-23e-NZuapzHg3X9TaN1iIixfv1W23E.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```
Not sure if I read the signs correctly but it looks like Auth0 client library returns `null`.

![screen shot 2018-08-11 at 07 50 56](https://user-images.githubusercontent.com/450975/43988755-6b41509e-9d3c-11e8-88c5-521764af2084.png)

**Comment by jlengstorf** [comment]
Thanks, @stlk! This definitely seems like something that Safari doesn't like about our code.

@lukeoliff a while back you had mentioned opening a PR to close #93 — I believe that would address this as well. Have you had the chance to look into this?

**Comment by Manoz** [comment]
Have the same issue on Chrome iOS. Looks like the website recognizes me but does not redirect me. 

If I go back I’m not logged in even after refreshing the page. 

http://imgur.com/rRL86C2

**Comment by jedrichards** [comment]
@jlengstorf @Manoz Safari is not tolerant of hashes on urls that don't have a trailing slash. So something to check is that your `AUTH0_CALLBACK` url has a trailing on it ...

https://community.auth0.com/t/hash-gets-lost-on-safari-webkit-browsers/7263/6
