### ISSUE TITLE
Don't require building gatsby-source-shopify-storefront

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/store.gatsbyjs.org#107]
It took me a little while to figure out why the site wasn't working. We could fix this by adding installation instructions perhaps or just writing vanilla node code that'll work w/o compiling.

**Comment by angeloashmore** [comment]
[`gatsby-source-shopify`](https://github.com/angeloashmore/gatsby-source-shopify) is available on NPM. It should provide the same data as `gatsby-source-shopify`, plus more.

**Comment by jlengstorf** [comment]
I did this because there wasn't a V2 branch of the plugin. Then I ended up writing a bunch of custom stuff to pull down images. Haven't had the chance to contribute this back up, but the goal is to get this into the original plugin again.

**Comment by camsloanftc** [comment]
I added comment over at [angeloashmore/gatsby-source-shopify/#1](https://github.com/angeloashmore/gatsby-source-shopify/issues/1). It seems this plugin is getting fragmented into parts. It would be great to have a single source to make PRs against, maybe moving under Gatsby monorepo, or just committing it back to the original repo by @angeloashmore.
