### ISSUE TITLE
Add redirect for shop.gatsbyjs.org to store.gatsbyjs.org

### ISSUE THREAD

**Issue by kkemple** [gatsbyjs/store.gatsbyjs.org#108]
I just tried to go to store via `shop.gatsbyjs.org` instead of using the proper subdomain `store` and was greeted with DNS not found error. I thought store was down, had to go repo and follow link there then compare to realize what I did. Others could experience this as well I think. Or maybe I'm just opening this to not feel like a dummy 😅.

**Comment by jlengstorf** [comment]
Hmm. I don't dislike the idea of adding a fallback redirect, but I wonder if that's worth it? I guess it's not hard to set up, so maybe we just do it?

**Comment by kkemple** [comment]
How about we reopen if someone else experiences it. We just don't have a way of knowing short of them submitting an issue about it.
