### ISSUE TITLE
Disable sold out products

### ISSUE THREAD

**Issue by kkemple** [gatsbyjs/store.gatsbyjs.org#110]
Currently users can pick any amount of any product and then when going to checkout are told when things are out of stock.

Could be a nice UX improvement to prevent adding sold out item to cart.

**Comment by jlengstorf** [comment]
Agreed. I'm trying to get a second wave of store work prioritized to tackle stuff like this.

**Comment by kkemple** [comment]
After v2 happy to jump in and help!

**Comment by jlengstorf** [comment]
Good call. Closing!
