### ISSUE TITLE
[Swag] Hats

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#115]
A good ball cap is a great piece of swag. I wear the hats I've gotten as swag all the time, so this seems like a good bet for useful swag.

A few styles I like: 

- [OTTO 83-561](https://ottocap.com/cotton-twill-low-profile-pro-style-mesh-back-caps-2.html)
- [Legacy Old Favorite Trucker](http://www.legacy92.com/styleItemClick?mstyItmID=1531&styId=8&chID=1&clID=2&msclID=4&mcolID=11&colID=1)

A lot of those Legacy caps look really nice. I own one and I really like it. Same with the OTTO; I probably wear that one most often, but it could also be because that's a black hat and it goes with everything. 🤷‍♂️

**Comment by m-allanson** [comment]
👍 for the [Legacy Military Cadet](http://www.legacy92.com/Style?styId=54&chID=1&clID=2&msclID=6&mcolID=13&colID=1).

**Comment by jlengstorf** [comment]
@m-allanson Are you employing that classic dry British humor right now, or do you really want us to try those hats out? I can order some samples if you like them.

**Comment by m-allanson** [comment]
Haha I genuinely want one!

**Comment by lindaleebumblebee** [comment]
I actually love the military style hat! I'll put it on the list of considerations.

**Comment by jlengstorf** [comment]
Purple hat mockup:

<img width="339" alt="screen shot 2018-09-05 at 4 56 27 pm" src="https://user-images.githubusercontent.com/163561/45127332-a9306a80-b12c-11e8-96b8-b20a40efe9e0.png">


Grey hat mockup:

![grey-hat](https://user-images.githubusercontent.com/163561/45127177-ec3e0e00-b12b-11e8-8001-4a9fa8bcc52b.jpg)

**Comment by jlengstorf** [comment]
Hats are live! store.gatsbyjs.org
