### ISSUE TITLE
[EPIC] Offer exclusive swag for different contribution levels

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#116]
> **NOTE:** This issue is an epic, which bundles up lots of related issues into a single goal. If you have the [free ZenHub extension](https://www.zenhub.com/), you’ll be able to see overall progress and related issues, as well as a "board view" that shows this epic from a bird's-eye view.

### Who will own this?

Role            | Contributor(s)
--------------- | -------------------------------
AoR owner       | @jlengstorf
Domain owner    | @jlengstorf
Project manager | TBD
Tech lead       | @jlengstorf
Contributors    | @jlengstorf, @lindaleebumblebee, @marisamorby

### Summary

We want to create swag that's _only_ available for contributors who submit certain types of PRs.

For example, maybe we have an exclusive t-shirt (or mug, or enamel pin, etc.) that you can _only_ get by submitting 5 docs PRs. Another that's only available if you submit 5 code PRs.

The general idea is that we want to go above and beyond to thank the members of the Gatsby community who go above and beyond for us. 💪💜

### How will this impact Gatsby?

**Domains**

- Swag store
- OSS process

**Components**

- Swag store

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project  is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase / decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go  wrong? What are the trade-offs? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

## Next Steps
- [x] Under `Pipeline` select `Proposed Epics` (only if you are NOT the AoR owner)
- [x] Under `Assignees` select the AoR Owner 
- [x] Under `Labels` select `Epic` 
- [x] Select `Create Epic`

**Comment by kkemple** [comment]
I think pins or badges would be easy/cheap to make

**Comment by jlengstorf** [comment]
Enamel pins would definitely be cool. We could almost do it like the scouts, where you would get different pins for different achievements, and if you got all of them you'd get something special.

I think our goal with the higher-effort stuff should be to make the swag higher value, too. Like maybe a high-quality travel mug, etc.

**Comment by lindaleebumblebee** [comment]
I agree on the enamel pins as they are easy to customize and they can look really cool. I like the scout idea....we could play with a vintage scout theme on the design. :)

**Comment by jlengstorf** [comment]
Right now it seems like a test run would make sense. Maybe ~50 of each design, and we could try 2–4 "merit badge" ideas.

I have a few ideas for criteria. What about something like this:

1. **Bug Patrol** — submit 5 pull requests that close bug issues
2. **Teacher** — submit 5 improvements to the docs
3. **Show & Tell** — give a Gatsby talk or workshop at an event
4. **Storyteller** — write a Gatsby tutorial or case study

There are definitely others, but I think these would be reasonably straightforward to verify (see PR histories and/or look at blogs, event websites) and are all really high-value contributions that we want to incentivize.

What do you think?

**Comment by jlengstorf** [comment]
Another idea in this realm: time-boxed "sprints" where we run exclusive swag and have special swag for different levels of contribution.

The evergreen flow would be that we have e.g. hoodies for contributors who submit a given number of PRs, but we could introduce short-lived swag tiers for high-priority projects.

As an example, let's say we wanted to get all of our existing docs stubs written over the next 6 weeks, and let's say there are 50 stubs. We could say:

- Anyone who submits a docs PR will get this limited run t-shirt.
- Anyone who submits 3 docs PRs will get a limited run mug/hoodie.
- Anyone who submits 10 docs PRs will get a really special thing — we'd have to decide what this is.

We could also wait until the end of the sprint to order, so we'd get exact numbers printed and control production costs.

This is similar to [Hacktoberfest](https://hacktoberfest.digitalocean.com/), but we could have projects like these running regularly and put them on any timebox that makes sense.

This could be a fun way to incentivize high-priority projects (e.g. current epics) and put some fun limited-edition swag into the world.

**Comment by marisamorby** [comment]
I do like the idea of an evergreen flow of exclusive swag for very active contributors and/or limited runs of swag for help with high-priority projects. I'd start with the evergreen swag and see how it's received.

I do like the idea of starting with badges to see how the initial idea pans out with people and what the response is.

**Comment by jlengstorf** [comment]
@marisamorby sounds good. We can do the evergreen setup first.

**Comment by calcsam** [comment]
Agree with @marisamorby -- love this idea, let's start with evergreen swag

**Comment by jlengstorf** [comment]
Leave me alone, @gatsbot, gosh!

**Comment by La-comadreja** [comment]
Just want to let you know we are a team of 3 attracted to this project by the swag.  So it is working.  Happy to discuss.
