### ISSUE TITLE
tier 2 swag: [design] Product detail pages

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#117]
As our inventory grows, it'll be nice to be able to link people directly to a particular product. This will also help with things like sizing guides, photos of community members wearing the swag, etc.

These pages will include:

- Larger images of the product
- Full description (previews are truncated)
- Sizing and care instructions
- Optional section for photos of contributors wearing/using the product
- Link to request a size if one is missing

We need designs for these, so @fk will need to get involved. Flo, what's your availability for taking this on?

**Comment by KyleAMathews** [comment]
Also that sweet sweet page transition speed.

**Comment by fk** [comment]
Oh man, thanks for assigning this to me Jason (and getting this back on my radar)!
Totally missed out on this up to now. 🙏 

Yay for this. Will take a good look at my backlog over the weekend and follow up!

**Comment by marisamorby** [comment]
@amberleyromo is this being accounted for in the swag store redesign? If so, can we close this?

**Comment by amberleyromo** [comment]
@marisamorby Actually, I'll just add this to the Epic. (Thanks for noting!) We had bundled product preview and product detail, makes sense to keep this and split it out.

**Comment by amberleyromo** [comment]
![screen shot 2019-01-03 at 2 49 37 pm](https://user-images.githubusercontent.com/3461087/50660852-d53aeb80-0f66-11e9-987c-0306ae9b1cb7.png)

Closed in #201
