### ISSUE TITLE
Make sure discount codes work for all of the contributor swag

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#12]
Currently the discount code only seems to work for the purple shirt — it _should_ allow contributors to get either the purple tee, dark deploy tee, or the socks for free.

Check this in the Shopify admin dashboard.

**Comment by marisamorby** [comment]
Note: Go into Shopify, edit the discount code and fix the selector so that it allows any swag product to be bought with discount code.

**Comment by marisamorby** [comment]
Discount code updated to work across all products.

Screenshots below:
<img width="543" alt="screenshot 2018-06-30 15 40 14" src="https://user-images.githubusercontent.com/13393126/42129541-feeb9c28-7c7b-11e8-9d32-b9cf76684eee.png">

<img width="525" alt="screenshot 2018-06-30 15 39 41" src="https://user-images.githubusercontent.com/13393126/42129543-02a1b500-7c7c-11e8-89bb-83120669f029.png">
