### ISSUE TITLE
[EPIC] Order new swag (hoodies etc)!

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#122]
> **NOTE:** This issue is an epic, which bundles up lots of related issues into a single goal. If you have the [free ZenHub extension](https://www.zenhub.com/), you’ll be able to see overall progress and related issues, as well as a "board view" that shows this epic from a bird's-eye view.

### Who will own this?

|                 |       |
| --------------- | ----- |
| AoR owner       | @jlengstorf |
| Domain owner   | @jlengstorf |
| Project manager | @name |
| Tech lead       | @name |
| Contributors    | @lindaleebumblebee, @jlengstorf, @marisamorby, @fk |

### Summary

We need to add additional swag to our store. This is required for https://github.com/gatsbyjs/store.gatsbyjs.org/issues/116.

### How will this impact Gatsby?

**Domains**

- Swag store

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  We have new swag items available for sale in the swag store
2.  We have higher-value swag available for use in tiered contributor rewards #116 
3.  We have the new swag available for sale within 5 weeks

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**Metrics to Measure Success**

- We see repeat sales in the store for existing contributors buying the new swag
- Once #116 is complete, we see repeat contributors claiming new swag as they reach new contribution milestones

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

- If we don't design swag people want, this could be expensive and low-impact

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

- What is our final lineup of new swag? (@jlengstorf will attach an initial list of proposed swag to this epic)

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

1. Identify the final list for the next round of swag
2. Put in orders with the supplier
3. Finalize details for fulfillment
4. Load the new swag into the swag store
5. Let it rip!

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

n/a — swag is swag

## Next Steps
- [x] Under `Pipeline` select `Proposed Epics` (only if you are NOT the AoR owner)
- [x] Under `Assignees` select the AoR Owner 
- [x] Under `Labels` select `Epic` 
- [x] Select `Create Epic`

**You're all done!**

**Comment by jlengstorf** [comment]
I've emailed for a quote on all the gear in the backlog (#38, #40, #51, #104, #115, #121). @lindaleebumblebee is copied on the email. We'll report back once we know how much we can reasonably produce right now.

**Comment by mikelax** [comment]
Pins and trucker hat 💯 

![Meme](https://i.kym-cdn.com/photos/images/original/000/620/799/57a.jpg)
