### ISSUE TITLE
[EPIC] Swag Store UX Improvements

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#123]
> **NOTE:** This issue is an epic, which bundles up lots of related issues into a single goal. If you have the [free ZenHub extension](https://www.zenhub.com/), you’ll be able to see overall progress and related issues, as well as a "board view" that shows this epic from a bird's-eye view.

### Who will own this?

Role            | Contributor(s)
--------------- | -------------------------------
AoR owner       | @jlengstorf
Domain owner    | @jlengstorf
Project manager | TBD
Tech lead       | @jlengstorf
Contributors    | @jlengstorf, @lindaleebumblebee, @marisamorby

### Summary

We have a lot of cleanup tasks for the swag store that need to be completed, as well as next steps (new swag https://github.com/gatsbyjs/store.gatsbyjs.org/issues/122 and contribution-based rewards https://github.com/gatsbyjs/store.gatsbyjs.org/issues/116).

This epic will bundle up the scope of work for phase 2.

### How will this impact Gatsby?

**Domains**

- Swag

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  Improve the UX of the swag store
2.  Eliminate annoying bugs like out-of-stock errors
3.  Add new features like larger image lightboxes to improve the store functionality

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

We'll know this epic is a success if:

- The outstanding UX issues are addressed in the repo
- The new features have been implemented successfully

#### Metrics to Measure Success

- Decreased UX issues for the store

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go  wrong? What are the trade-offs? Do we need to close a door to go through this one?_

If we don't get the UX right, we risk adding extra hurdles or frustration to the swag buying/claiming experience, which could deter contributors from getting involved.

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

We need the following resources:

- Limited design time to cover e.g. lightbox design and product detail pages
- Dedicated developer time to implement the changes

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

1. Finalize the scope of phase 2
2. Write out better issue descriptions of the work
3. Burn through the issues

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

Nope. Just have to do the work.

## Next Steps
- [x] Under `Pipeline` select `Proposed Epics` (only if you are NOT the AoR owner)
- [x] Under `Assignees` select the AoR Owner 
- [x] Under `Labels` select `Epic` 
- [x] Select `Create Epic`

**Comment by jlengstorf** [comment]
TODO: narrow scope of this, create follow-up epics for the work we're not going to do this time around.

**Comment by andrew-anguiano** [comment]
@jlengstorf I was going to open an issue and work to try and add a lightbox for the store item images. I saw that that feature is mentioned here, but this issue is closed so I was wondering if that was still something that would be good to work on.
