### ISSUE TITLE
Add better handling for out-of-stock items

### ISSUE THREAD

**Issue by lightstrike** [gatsbyjs/store.gatsbyjs.org#124]
I hit this error when trying to add a SM Unisex Dark Deploy Tee:

![screenshot from 2018-08-27 09-50-17](https://user-images.githubusercontent.com/1368742/44672932-db302700-a9de-11e8-9a35-f90f6707c3f0.png)

Maybe it's out of stock?

**Comment by coreyward** [comment]
Hey @lightstrike, I suspect you're right about it being out of stock. When I pull up the site the variant you selected isn't even an option:

![screen shot 2018-08-30 at 10 26 25 am](https://user-images.githubusercontent.com/81224/44861925-3d876280-ac3f-11e8-91f3-ef2d055e5506.png)

**Comment by jlengstorf** [comment]
@lightstrike Yeah, it looks like @coreyward is right. We've got an order in to get things back into stock, so sit tight. We're also about to start working on #123 to clean up the UX on the store, which should address this and other annoying bugs we've spotted since it first launched.

**Comment by dumblole** [comment]
It works for me, is this still an issue. Is the fix supposed to be removing the ability to select these items or the fact that the sidebar still charges for these items.  
![image](https://user-images.githubusercontent.com/28949652/46384364-78881600-c683-11e8-8644-791b59d8d0e4.png)

**Comment by jlengstorf** [comment]
@dumblole Ideally, the UI of the store would show items as disabled rather than letting you get all the way to checkout before telling you it's sold out. Shopify returns items with "variants" (the sizes, etc.) that each have an inventory count attached, so we need to check if the variant has >=1 in inventory, and disable the option if not.

**Comment by dumblole** [comment]
Alright @jlengstorf  thanks for clearing it up, I'll take a look when I come home from school later today. I'd appreciate a couple of pointers if it wouldn't bother you too much.

**Comment by jlengstorf** [comment]
@dumblole Of course!

A few key pieces of code:

The product details are loaded here: https://github.com/gatsbyjs/store.gatsbyjs.org/blob/df6969a0757a91962871682724d0d2e9d2735fd3/src/components/Store/ProductListings.js#L29-L33

There’s an `availableForSale` field that will tell you whether or not each variant is in stock. Add that to the query. (Try it out [in GraphiQL while running `gatsby develop`](http://localhost:8000/___graphql) to see it working.)

Products with multiple variants (e.g. sizes) are set up here: https://github.com/gatsbyjs/store.gatsbyjs.org/blob/df6969a0757a91962871682724d0d2e9d2735fd3/src/components/ProductPreview/AddToCart.js#L122-L126

We need to add a check for whether or not that option is available for sale, and disable it if not.

Finally, for products with one variant (i.e. stickers and socks) we need to disable the whole product, probably by disabling the "add to cart" button and changing the text to "sold out". This will require the most refactoring, but I believe it's all contained in `AddToCart`.

Let me know if you need any additional pointers!

**Comment by dumblole** [comment]
@jlengstorf Thanks for the opportunity for contributing. Thanks for the really really helpful pointers - I don't think I would've figured out the code. Even though I added like 3 lines of code, I have learned a lot. Nevertheless, there's a lot I still have to learn.

**Comment by AlexanderProd** [comment]
How do you currently handle updating the site when something is bought and the Shopify inventory changes? I couldn't find any dynamic availability checking of the items so I'm assuming you're rebuilding and redeploying the site everytime a purchase happens to keep the inventory updated? @jlengstorf

**Comment by jlengstorf** [comment]
@AlexanderProd You're correct. Shopify has webhooks support, so we use that to trigger a Netlify rebuild whenever inventory changes.

**Comment by abohannon** [comment]
@jlengstorf does triggering a build every inventory change cause you to blow through your build minutes in Netlify? I imagine a busy store, even with incremental builds, would exceed the quota pretty quickly?

**Comment by jlengstorf** [comment]
@abohannon it definitely could, yeah. a way to handle that without rebuilding every time is a client-side inventory check
