### ISSUE TITLE
Customer information does not meet the requirements for the [code] discount code

### ISSUE THREAD

**Issue by merelinguist** [gatsbyjs/store.gatsbyjs.org#133]
When trying to checkout with the discount code I received for Gatsby contributions, I receive the following error when choosing the shipping method:

![screenshot_2018-09-04 shipping method - gatsby store - checkout](https://user-images.githubusercontent.com/24858006/45057736-586a3480-b08e-11e8-8f03-03bb93bc2149.png)

**Comment by jlengstorf** [comment]
@merelinguist Hey there! I took a look, and it appears we had a hiccup while creating your discount code. I just kicked it, and it _should_ work now. Give it a shot and, if it works, we'll close this.

Thanks!

**Comment by merelinguist** [comment]
Super! That worked 💜
