### ISSUE TITLE
Inconsistent OG Tags for store.gatsbyjs.org

### ISSUE THREAD

**Issue by mikelax** [gatsbyjs/store.gatsbyjs.org#134]
## Description

When viewing the gatsbyjs store through something that lints the page, ie. the Facebook Debugger the OG tags and thus rendered display are not correct. The current values are a mix of values from both the black t-shirt and socks. They should be more general and apply to a storefront, not a single item (that would make sense if each item had its own URL). 

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

The OG tags should be consistent and make sense for a general store homepage. 

### Actual result

Here is the result of what I am seeing in the Facebook debugger. 
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fstore.gatsbyjs.org%2F

| og:url | https://store.gatsbyjs.org/ |
| ------------- | ------------- |
og:type | website
og:title | Gatsby Store
og:image | https://store.gatsbyjs.org/static/d8979cd87644af7316a8554e83511d5d-a3a6c096c4ab226d2c24cce771e5463a-63db5.jpg
og:description | Get your feet into these black socks with a Gatsby purple border and heel. The bright pops of color keep it fun while keeping you warm.
og:updated_time | 1536327762
ia:markup_url |  
ia:markup_url_dev |  
ia:rules_url |  
ia:rules_url_dev |  
| og:image:alt | Dark Deploy Tee |

### Environment

Visit https://store.gatsbyjs.org and view the OG tags, or run the URL through the [Facebook Debugger](https://developers.facebook.com/tools/debug/).

**Comment by jlengstorf** [comment]
Oh, whoops. Good catch, @mikelax! This is definitely a great first issue, and I'm available to help out if anyone wants to take this!

**Comment by junhyukee** [comment]
Could this be done via Helmet? I would love to try and tackle this issue as my first issue!

**Comment by cometkim** [comment]
@junhyukee I apologize for being intercepted your first issue.. :bowing_man:

**Comment by junhyukee** [comment]
@cometkim LOL no worries!! I will find more to work on! 😄

**Comment by mikelax** [comment]
oh nice @cometkim @junhyukee 
This is something that definitely should be done through Helmet, perfect use of it.
