### ISSUE TITLE
Contributor's discount not working

### ISSUE THREAD

**Issue by junhyukee** [gatsbyjs/store.gatsbyjs.org#139]
Getting the contributor's discount error, potentially due to entering my information a few weeks ago 😢. 
![discounterror](https://user-images.githubusercontent.com/35748067/45465144-b9b28900-b6c8-11e8-9f9a-64b5dd5f5516.png)

**Comment by jlengstorf** [comment]
Hey, @junhyukee — that's what happened. Sorry about that! I've created #140 to track fixing this bug. In the meantime, I updated your account and you should be able to claim the discount now.

Thank you!
