### ISSUE TITLE
[Browser support] fetch is undefined - missing polyfill?

### ISSUE THREAD

**Issue by lloydh** [gatsbyjs/store.gatsbyjs.org#154]
Just a heads up that the site crashes IE 11 on account of fetch being undefined. As there's not a ``browserslist`` entry in ``package.json`` my understanding is that Gatsby v2 supports [``>0.5, not dead``](https://www.gatsbyjs.org/docs/browser-support/#browser-support), which _should_ include a fetch polyfill for IE 11 via Babel 7 ``preset-env``.

Obviously not many Gatsby devs will be using IE as their primary browser but I came across this repo as a reference Shopify implementation so IE support would be great to see.

**Comment by jlengstorf** [comment]
Oh, whoops — yeah, this would be great to get fixed.

Is anyone looking to wrap up their Hacktoberfest PRs? This would be a good candidate for that!

Potential fixes:

- [ ] Swap out `fetch` for `axios` (which I believe eliminates this problem altogether)
- [ ] Add the appropriate `fetch` polyfill

I'm happy to answer questions on this. Thanks again for bringing this up, @lloydh!

**Comment by DSchau** [comment]
@jlengstorf +1 for axios! Simplifies some of the code for fetching, and uses `XMLHttpRequest` under the hood, therefore reducing the need for a polyfill.

**Comment by lloydh** [comment]
It seems that it's the ``shopify-buy`` client that is using fetch. [It's simple](https://github.com/Shopify/js-buy-sdk/issues/458#issuecomment-352070407) to pass the constructor a specific fetch implementation (polyfill) but I'm not sure whether using axios is feasible.

**Comment by jlengstorf** [comment]
Ah... that complicates things. Looks like _only_ the polyfill is viable, then. Or this issue moves upstream to the Shopify Buy SDK.

**Comment by jlengstorf** [comment]
@aestevens Thanks! It's all yours. 💪💜

**Comment by hackily** [comment]
It might be worth checking how other browsers are behaving.
The production site doesn't work for me on firefox 62, nor does the site compiled with `gatsby build`.

I can't get to the auth0 page, open the cart, or add things to the cart. However, cloning the repo and running `gatsby develop` brings up the dev server with perfect functionality.

Interesting.

**Comment by jlengstorf** [comment]
Hmmm... that seems... bad. We should definitely dig deeper into this. I'm just starting a reasonably intense refactor of this site to use a new back-end, so I'll make sure to include this in that work.

**Comment by jlengstorf** [comment]
I just checked on macOS using Firefox 60 and things worked. I then updated to Firefox 63 and things are still working for me. @hackily do you have any errors on your end?

**Comment by hackily** [comment]
Oh hell. I have greasemonkey and I isolated the reason why it won't work for me to reek's anti-adblock killer script: `https://reek.github.io/anti-adblock-killer/`

Without it, the prod site works, and so does the local prod build.

**Comment by jlengstorf** [comment]
@hackily phew! Glad to hear that; I was worried we'd shipped broken code. 😅

**Comment by jlengstorf** [comment]
Does anyone have access to IE11 to test this out? the Shopify Buy SDK _should_ be shipping a polyfill, and our code is using axios now. @greglobinski did you happen to do any IE11 testing when you were building the new design?

(Also, do we care? @lloydh brings up two good points: 1. this is a site for an audience that's almost certainly not using IE, and 2. this is also being passed around as a canonical example of ecomm, so IE support might be worth it.)

**Comment by jlengstorf** [comment]
@greglobinski okay. I'm inclined to leave IE11 support as an exercise for the reader, then. The trade-off to keep monitoring IE11 isn't worth it given our audience. I'll mark this one as a wontfix (though it might actually be fixed).

**Comment by greglobinski** [comment]
This fetch issue probably could be fixed, but I'm afraid that the UI will not work as we expect in IE11.
