### ISSUE TITLE
Remove issues that have the `Hacktoberfest - Claimed` label

### ISSUE THREAD

**Issue by ItsPugle** [gatsbyjs/store.gatsbyjs.org#155]
Since issues that have the `Hacktoberfest - Claimed` labels are already being developed by a Hacktoberfest participant, I think it would be good if the store didn't list them as open issues on the Maintainer Dashboard. 

For example, this issue is advertised even though it's already being developed:
![2018-10-26 at 10 44 am](https://user-images.githubusercontent.com/22669894/47538000-437e8480-d90c-11e8-817c-a57ac24671bc.png)

**Comment by jlengstorf** [comment]
Oh, this is actually a _great_ idea, and a great Hacktoberfest issue. 😅 

Anyone want to pick this up?

**Comment by brandonmbanks** [comment]
I would be happy to work on this!

**Comment by brandonmbanks** [comment]
@jlengstorf I have a PR that would address this issue. Let me know if you have any comments.

**Comment by ItsPugle** [comment]
Great work squad 🌟
