### ISSUE TITLE
tier 2 swag: [shopify] add tier 2 tag to shopify customer

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/store.gatsbyjs.org#171]
Add a new tag to shopify customer that indicates they're tier 2.

**Comment by jlengstorf** [comment]
Relevant code in the API: https://github.com/gatsbyjs/api.gatsbyjs.org/blob/dbe21afbc6e5a22adf5c507025121569783d92f9/src/lib/shopify.js#L14-L37

**Comment by amberleyromo** [comment]
https://github.com/gatsbyjs/api.gatsbyjs.org/blob/679ea4ef0f6f24d650d4ad765ca58c8be7fd403a/src/lib/shopify.js#L163
