### ISSUE TITLE
tier 2 swag: [design] Handle used coupon codes for logged-in users

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/store.gatsbyjs.org#176]
If a user logs in to the store, and is qualified for swag (currently only tier-one swag), the UI shows the same coupon code flow whether they've redeemed swag or not. 

If a user has already logged in and redeemed swag, the coupon code should show a "used" state of some sort.

**Comment by jlengstorf** [comment]
Related: #169

**Comment by amberleyromo** [comment]
![screen shot 2019-01-03 at 3 20 50 pm](https://user-images.githubusercontent.com/3461087/50662195-3369cd80-0f6b-11e9-83e1-f2737d441347.png)

https://gatsbyjs.slack.com/archives/CDX7WM937/p1546005472001300
