### ISSUE TITLE
tier 2 swag: [design] enhance product preview

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/store.gatsbyjs.org#177]
Enhance product preview. (Lightbox? Open for discussion)

**Comment by jlengstorf** [comment]
Ideally, we'll have:

1. A product detail page with a unique URL
2. A lightbox feature for photos

Both should probably start with a design phase, so we probably need to have issues splitting that out.

**Comment by amberleyromo** [comment]
Implemented in #201
