### ISSUE TITLE
tier 2 swag: [design] allow filtering by product tiers and other attributes

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/store.gatsbyjs.org#180]
Design a solution for making it visually apparent which items are available as part of which contributor tier.

Relates to #173

**Comment by jlengstorf** [comment]
To make this work in Shopify:
1. Add the product to the correct collection (e.g. "Level 1 Swag", "Level 2 Swag")
2. Add the corresponding tag (e.g. "level 1")

**Comment by amberleyromo** [comment]
Product filtering design included in redesign Figma: https://www.figma.com/file/giueJlbA96riSuEiYgGPBq2W/swag.store.tier2?node-id=0%3A1

![screen shot 2019-01-03 at 3 06 51 pm](https://user-images.githubusercontent.com/3461087/50661607-44b1da80-0f69-11e9-826f-53025bab6a32.png)
