### ISSUE TITLE
'Visit our store' link in Gmail sends user to shopify store.

### ISSUE THREAD

**Issue by aesthytik** [gatsbyjs/store.gatsbyjs.org#184]
Here is link on gmail:
![order 1957 confirmed rawat vipin4818 gmail com gmail](https://user-images.githubusercontent.com/26917061/48317983-a3b93a00-e61f-11e8-80b3-12bfad091ac7.png)

it redirects to shopify store instead of gatsby store:
![gatsby store opening soon](https://user-images.githubusercontent.com/26917061/48317990-b5024680-e61f-11e8-88ad-95d9dc7b1cc7.png)

**Comment by jlengstorf** [comment]
Hmm... I'll try to find that template. 😕 

Thanks for the heads up!

**Comment by isaac-martin** [comment]
@jlengstorf did you fix this? Its obviously not major, but i know exactly where it is and would be willing to fix for you!

**Comment by jlengstorf** [comment]
@isaac-martin I haven't fixed it yet, no. I'm out of seats for our Shopify account, but if you let me know where to look so I don't have to Google it I'll absolutely get you set up with a discount code for the assist. 😅

**Comment by jlengstorf** [comment]
@isaac-martin that did it! If you want to send me a note at jason@gatsbyjs.com, I'll get you set up with a discount code. Thank you!
