### ISSUE TITLE
Question: access denied

### ISSUE THREAD

**Issue by NormanPerrin** [gatsbyjs/store.gatsbyjs.org#185]
### intro
Hello.
Maybe unrelated to the repo but I had a problem cloning your repo and trying to run it with my Shopify private app credentials.

### problem
When it starts building, it fails with this query:
```
{
  shop {
    products(first: 10) {
      pageInfo {
        hasNextPage
      }
      edges {
        cursor
        node {
          createdAt
          description
          descriptionHtml
          handle
          id
          images(first: 250) {
            edges {
              node {
                id
                altText
                originalSrc
              }
            }
          }
          onlineStoreUrl
          options {
            id
            name
            values
          }
          priceRange {
            minVariantPrice {
              amount
              currencyCode
            }
            maxVariantPrice {
              amount
              currencyCode
            }
          }
          productType
          publishedAt
          tags
          title
          updatedAt
          variants(first: 250) {
            edges {
              node {
                availableForSale
                compareAtPrice
                id
                image {
                  altText
                  id
                  originalSrc
                }
                price
                selectedOptions {
                  name
                  value
                }
                sku
                title
                weight
                weightUnit
              }
            }
          }
          vendor
        }
      }
    }
  }
}
```

The error of the message is `access denied`.
I'm really not sure what the permission problem would be since it has this permissions:
<img width="617" alt="captura de pantalla 2018-11-25 a la s 10 57 39" src="https://user-images.githubusercontent.com/11911371/48979949-0212fd80-f0a1-11e8-8050-cb91279adb70.png">

Thanks in advance.

**Comment by jlengstorf** [comment]
Hi @NormanPerrin! I'm not sure what the problem could be at first blush, but make sure you've got your Shopify access token set. (see https://github.com/gatsbyjs/store.gatsbyjs.org/blob/master/gatsby-config.js#L13)

If that's set, you may want to try making a request through Shopify's API directly to make sure your token is working correctly. 

If the direct calls are working, maybe this is a plugin issue?

**Comment by NormanPerrin** [comment]
I had the access tokens according to my account.
For what I saw searching it might be a problem when some collection are empty, like blogs.
I dind't have problems doing direct calls from the GraphiQL.

But my free trial of Shopify expired 😕
So if I have to use use it later I'll comment my solution.
