### ISSUE TITLE
Add international shipping message to Shopify cart.

### ISSUE THREAD

**Issue by lindaleebumblebee** [gatsbyjs/store.gatsbyjs.org#187]
Let's add a warning about international shipping to the Shopify cart so we're setting the right expectation. It should say something like:

'International Shipping is unpredictable and slow! Please be advised that the shipment might take much longer than expected.'

**Comment by AnushPatel** [comment]
Maybe make this 'International shipments can take up to 6 weeks to be delivered. 😱 Tracking updates may not always show up in real time on your tracking link. If you still have not received your order at the end of 6 weeks, please let us know by sending an email to team@gatsbyjs.com, and we'll see how we can help!' a bit more clearer on the page?

**Comment by AnushPatel** [comment]
That's good! I wonder where the code is to add that so we can submit a PR?

**Comment by AnushPatel** [comment]
Also Sorry for my formatting! I messed that up

**Comment by AnushPatel** [comment]
Thanks, @jlengstorf! I will take a look at the code and give it a shot to get the message added. Looked at the new design screenshots in this repo and it looks great! Can't wait for it!
