### ISSUE TITLE
Change the auth0 domain to reference Gatsby

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#19]
The Auth0 setup is currently using my account (jlengstorf.auth0.com). Ideally, this will use a Gatsby-related login link. When I checked, our company name was already taken, so we need to see if someone already claimed this.

cc: @KyleAMathews @calcsam

**Comment by jlengstorf** [comment]
I'm hoping I can just _transfer_ instead of having to reconfigure the app under a new Auth0 tenant. Question is open: https://community.auth0.com/t/is-it-possible-to-transfer-an-app-to-a-new-tenant/12514

If I haven't heard back by Monday, I'll just reconfigure new apps.

**Comment by jlengstorf** [comment]
I got [an answer on this](https://community.auth0.com/t/is-it-possible-to-transfer-an-app-to-a-new-tenant/12514/2) a while back. This doesn't really feel like a pressing need, so I'm going to deprioritize it.

**Comment by yeskunall** [comment]
@jlengstorf I feel like this issue should be revisited by you guys. I just got my invite today and I actually noticed the URL. Had I not known you worked for Gatsby, it would have definitely raised my suspicion. 🤭

**Comment by jlengstorf** [comment]
Yeah, it's definitely on the list of things to do. 😅
