### ISSUE TITLE
Cloned to local, clicked add to cart but nothing happen

### ISSUE THREAD

**Issue by gddabe** [gatsbyjs/store.gatsbyjs.org#194]
I didn't setup api.gatsby.org, how can I get rid of it and let it run properly in local?

**Comment by jlengstorf** [comment]
@gddabe To add things to a cart, you'll need to have a Shopify store set up with the appropriate tokens. See https://github.com/gatsbyjs/store.gatsbyjs.org/blob/625b0299f625303ad610d22611f9d878e8f50cfa/src/context/StoreContext.js#L4-L7

And https://github.com/gatsbyjs/store.gatsbyjs.org/blob/625b0299f625303ad610d22611f9d878e8f50cfa/gatsby-config.js#L9-L15

Hope that helps!

**Comment by gddabe** [comment]
it works! cheers!

**Comment by jlengstorf** [comment]
I should probably move all of this into a `.env` or something, because that's confusing. 😅
