### ISSUE TITLE
Make it easier to dismiss the "Your Cart" overlay

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#20]
Make it easier to dismiss the "Your Cart" overlay - add a close button, detect clicks outside the overlay or detect pressing esc?

**Comment by kkemple** [comment]
So far our Storybook integration consists of some form inputs in the .com site. There is absolutely no reason NOT to make it public and I would actually prefer to! This would require a new package and moving storybook and components into said package. This way all properties can install and make use of them. We should figure out where this lives as far as priority as it will only get harder the further along we get.

On the flip side to that, pulling out components too early and enforcing DRY too much can lead to process/workflow slowdown. My recommendation is let's just put it in for now once it's implemented if the use cases are close enough and API flexible enough we hoist it out then.

My 2¢

**Comment by jlengstorf** [comment]
This is half-done now. @fk added a close icon, but we haven't added the "click anywhere outside the cart to close" functionality.

Moving this to Phase 2 because it's not a blocker.
