### ISSUE TITLE
[redesign] Add internal ads 

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/store.gatsbyjs.org#203]
Addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/201

Although I designed two different shapes of the "Free Sticker Pack" ad, for desktop and mobile, now I think that for flexibility and future use we should stay with one, the desktop version, which fits to both viewports. 

![screenshot from 2019-01-03 17-19-24](https://user-images.githubusercontent.com/32480082/50648687-273a3c00-0f7c-11e9-9fac-c6c86394a350.png)

![screenshot from 2019-01-03 17-21-08](https://user-images.githubusercontent.com/32480082/50648685-26a1a580-0f7c-11e9-9b58-66609d885841.png)

**Comment by jlengstorf** [comment]
This will be implemented as an image, so basically a banner ad. We're doing this so we can easily swap out for different information without needing to rewrite a bunch of markup/styles.
