### ISSUE TITLE
[redesign] Add filtering 

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/store.gatsbyjs.org#204]
I'm not sure if there is any reason to implement now or later (before we add any other filters besides codes) filter component as a full screen popup (the same way as the picture browser works). I would rather build a collapsible inline component. Clicking on "Filter Product list" would unfold the available option of filtering (in our case only by codes) 

That needs probably a small mockup from me. I will add it tomorrow.  

![screenshot from 2019-01-03 17-52-16](https://user-images.githubusercontent.com/32480082/50650310-5fdc1480-0f80-11e9-9bff-070de2c39a64.png)
![screenshot from 2019-01-03 17-51-34](https://user-images.githubusercontent.com/32480082/50650311-6074ab00-0f80-11e9-8daf-f61fc07b6dcd.png)

**Comment by jlengstorf** [comment]
A mockup sounds good. Thanks, @greglobinski!

**Comment by greglobinski** [comment]
Originally I thought that the filtering feature will be available only for logged in users with at least one swag code.

But after reading Sam's comment on Slack
https://gatsbyjs.slack.com/archives/CAZJ6N0UT/p1546620405004800 I decided to try to combine the two: product thumbnails & product filtering, and below is the result. Tell me what do you think. 


Mockups are at Figma https://www.figma.com/file/giueJlbA96riSuEiYgGPBq2W/swag.store.tier2?node-id=0%3A1

![screenshot from 2019-01-07 14-48-14](https://user-images.githubusercontent.com/32480082/50771821-0c254000-128c-11e9-8cf1-769f6540ce6a.png)
![screenshot from 2019-01-07 14-49-08](https://user-images.githubusercontent.com/32480082/50771818-0c254000-128c-11e9-882f-f68a4e6955f0.png)
![screenshot from 2019-01-07 14-48-48](https://user-images.githubusercontent.com/32480082/50771819-0c254000-128c-11e9-8699-c4728f716c87.png)


![screenshot from 2019-01-07 14-50-11](https://user-images.githubusercontent.com/32480082/50771817-0c254000-128c-11e9-8f43-b757de9d0f29.png)
