### ISSUE TITLE
[redesign] Add a swag code flag to product page 

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/store.gatsbyjs.org#206]
Addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/201

For logged in contributor with valid code(s) the same way as we flag eligible products for code on Product listing we should flag them on the product pages.

> 10$ or free with the code

![screenshot from 2019-01-03 17-47-34](https://user-images.githubusercontent.com/32480082/50650105-d3315680-0f7f-11e9-995b-9c5349caadd4.png)

**Comment by jlengstorf** [comment]
This is done using the product group from Shopify. We may need to update the GraphQL query to retrieve this.

**Comment by greglobinski** [comment]
If so pleas also update the code in `ProductListingItem` 

https://github.com/greglobinski/store.gatsbyjs.org/blob/gl/full-redesign/src/components/ProductListing/ProductListingItem.js

because there I join a code with a product testing the price
```
 const freeWith =
    price >= 20 ? 'LEVEL2' : price >= 10 ? 'BUILDWITHGATSBY' : null;
```

**Comment by jlengstorf** [comment]
Okay, great. Will do.
