### ISSUE TITLE
[redesign] Add incentive to level up

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/store.gatsbyjs.org#207]
Addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/201

This how it looks like now. Regrettably I did not make any mockup visualizing @amberleyromo 's idea of progress bar. 

![screenshot from 2019-01-03 16-22-48](https://user-images.githubusercontent.com/32480082/50645519-0ff75080-0f74-11e9-9736-efb57d0be0a7.png)

![screenshot from 2019-01-03 16-25-17](https://user-images.githubusercontent.com/32480082/50645592-36b58700-0f74-11e9-8d7d-1fa59f73b6d4.png)

**Comment by jlengstorf** [comment]
A progress bar should be reasonably straightforward. I think we can manage. Thanks, @greglobinski!

**Comment by amberleyromo** [comment]
Thoughts on this?

<img width="420" alt="screen shot 2019-01-04 at 4 03 50 pm" src="https://user-images.githubusercontent.com/3461087/50713713-b0fd0e80-103b-11e9-8672-f10663ca997c.png">

**Comment by greglobinski** [comment]
I like it. Two thoughts:
- maybe instead of padlock, a couple of stars like in password input ******
- for the progress bar background I would try the 'brandDarker' color

**Comment by greglobinski** [comment]
"Make 1 more contribution to reveal Level 2 Swag Code"?

**Comment by greglobinski** [comment]
Nothing against the padlock, just was thinking aloud

**Comment by amberleyromo** [comment]
Closed with #213
