### ISSUE TITLE
[redesign] Extend the message for contributors who used already both of their swag codes 

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/store.gatsbyjs.org#208]
Addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/201

This is how the contributor area looks now for contributors who used their both codes. I think that we can say more :)

![screenshot from 2019-01-03 16-10-56](https://user-images.githubusercontent.com/32480082/50644815-3caa6880-0f72-11e9-8291-5f1cafd601b8.png)

![screenshot from 2019-01-03 16-11-09](https://user-images.githubusercontent.com/32480082/50644813-3c11d200-0f72-11e9-9de2-585db4643264.png)

**Comment by greglobinski** [comment]
This is how the contributor area looks now for contributors who used their both codes. I think that we can say more :)

![screenshot from 2019-01-03 16-11-09](https://user-images.githubusercontent.com/32480082/50644813-3c11d200-0f72-11e9-9de2-585db4643264.png)
![screenshot from 2019-01-03 16-10-56](https://user-images.githubusercontent.com/32480082/50644815-3caa6880-0f72-11e9-8291-5f1cafd601b8.png)

**Comment by jlengstorf** [comment]
Some initial thoughts here:

1. We can probably hide the bottom purple banner altogether if there’s no action to be taken.
2. We need to think about what the call to action is if someone has claimed both coupon codes. Is there one? If not, we can just say something nice.

**Comment by amberleyromo** [comment]
I think there's currently no further CTA needed. I added "something nice" language in my last PR. It feels like it's missing the "see open issues", contribution count, recent contributions, etc, but if we're going to conceive of this as a wider dashboard in future work, I think this will suffice for the current iteration.

<img width="420" alt="screen shot 2019-01-04 at 12 01 59 pm" src="https://user-images.githubusercontent.com/3461087/50703098-abda9800-1018-11e9-9f21-bbb6f611defe.png">

**Comment by greglobinski** [comment]
This is exactly what I was thinking of but I would never phrase it so nicely myself :100:, even in Polish   :smile:
