### ISSUE TITLE
[redesign] Restyle the used code badge

### ISSUE THREAD

**Issue by greglobinski** [gatsbyjs/store.gatsbyjs.org#209]
Addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/201

I did not finish styling the used code badge and think it needs to be done. With current view, the used code do not differentiate enough from the valid one. 

![screenshot from 2019-01-03 16-14-32](https://user-images.githubusercontent.com/32480082/50645079-015c6980-0f73-11e9-9c09-eac403d5321b.png)

Use the design from Figma.

![screenshot from 2019-01-03 16-15-08](https://user-images.githubusercontent.com/32480082/50645078-015c6980-0f73-11e9-9200-544bbf55b5a7.png)

**Comment by jlengstorf** [comment]
I think I'd like to make this more of a celebratory thing, now that I'm thinking about it.

So maybe instead of showing the cross and "already used", we could show a 🎉 or something and show "claimed!"

Like, we're _stoked_ that people are using these codes and want them to be stoked, too. 😄

**Comment by amberleyromo** [comment]
What do we think of something like this? (current state is on the right). Darkened background, text comparably smaller, but the badge look is more consistent (which I prefer personally). Also I think the slight text swap in the badge titles helps a lot.

<img width="680" alt="screen shot 2019-01-04 at 10 27 33 am" src="https://user-images.githubusercontent.com/3461087/50698752-68c5f800-100b-11e9-85f6-bb44c7c5a6b1.png">
