### ISSUE TITLE
Cannot add items to cart

### ISSUE THREAD

**Issue by jsjoeio** [gatsbyjs/store.gatsbyjs.org#214]
### Problem:

As a user, I cannot add items to the cart on the [Gatsby Store](https://store.gatsbyjs.org/). 

### Steps to Reproduce:

1. Go to the [Gatsby Store](https://store.gatsbyjs.org/)
2. Select the size for any item then click add to cart

### Expected:

Item is added to cart.

### Actual:

Nothing happens.

In the console, I'm seeing this error appear when I try to add something to the cart:

```js
index.js:3573 Uncaught (in promise) TypeError: Cannot read property 'checkoutLineItemsAdd' of undefined
    at index.js:3573
```

Looks like it's happening inside the function called `handleCheckoutMutation` on this line
```js
var rootData = data[mutationRootKey];
```

**Comment by jlengstorf** [comment]
Hey, @jsjoeio — are you still seeing this? I can't reproduce, so I'd love to get more information about your browser if you're still seeing this error.

Thanks!

**Comment by jsjoeio** [comment]
Weird. @jlengstorf Now it's working as expected. I'll close this.
