### ISSUE TITLE
[Bug] No way to close overlays for Materials & Fit and Care Instructions displays

### ISSUE THREAD

**Issue by mikelax** [gatsbyjs/store.gatsbyjs.org#238]
# Overview

As a user, when I am browsing the product details page, ie. [/product/dark-deploy-tee](https://store.gatsbyjs.org/product/dark-deploy-tee), If I click on either the *Materials & Fit* and *Care Instructions* Links a full page overlay is displayed. It takes up the full screen, but there is no way to dismiss or close the overlay to get back to the content you were looking at. 

If you are going to stick with this as a modal (I think I saw some discussion of moving to a separate page, #89 ) then there needs to be an **X** close button.

**Comment by jlengstorf** [comment]
Oh, whoops. Yeah, that definitely needs to be fixed.

**Comment by jlengstorf** [comment]
So, looking at this, it actually _does_ open a new page: https://store.gatsbyjs.org/product-details#materials-fit

The back button works as expected, so this isn't necessarily a bug, but more of a UX issue: **it's not obvious that this is how it works.**

Something that could be done to address this would be to add a button that uses the history object to navigate back to the product (similar to the "back to product list" button on the product page). If no previous product is found, it could default to "back to product listings".

Does that seem reasonable? If so, any takers to implement this?

**Comment by isaac-martin** [comment]
Yeah I can do this Jason. @jlengstorf

**Comment by mikelax** [comment]
thanks @jlengstorf and @isaac-martin . 
I think when I wrote up this ticket originally it was before the current design. 
In the new (current) I agree the problem is just a UX issue where the user should be given some option (besides browser back button) to get back to the product they were just looking at. 


I agree that either of these options would work:

* Add a Back to Product button
* Add a close (x) button right-aligned with page header that would "act" like a modal close button but would just navigate the user back to the previous page.

**Comment by jlengstorf** [comment]
Both options make sense. I think my preference would be for the back button. With the URL changing, an "X" could be really confusing if someone _did_ notice that the URL changed. 😄

**Comment by jlengstorf** [comment]
@isaac-martin hey, how’s it going? Have you had a chance to look at this? No pressure or anything — just let me know if you’re still planning to tackle this one so I can share it around if not.

Thanks!

**Comment by isaac-martin** [comment]
I've got a branch started, but have been hunting a new job so all spare
time has been dedicated to that. Someone else could tackle it.

**Comment by jlengstorf** [comment]
Sounds good, and good luck on your hunt!
