### ISSUE TITLE
Update Gatsby Contributor information

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#24]
* Make it clearer on the homepage that Gatsby contributors can claim a discount code?
* Make it clearer what the discount code entitles you to? "one-time code valid for one free item from the store"

**Comment by jlengstorf** [comment]
Love this!

**Comment by marisamorby** [comment]
This is cooooool! 💯

**Comment by jlengstorf** [comment]
This should be closed by #83
