### ISSUE TITLE
Set redirect In `header.liquid`

### ISSUE THREAD

**Issue by isaac-martin** [gatsbyjs/store.gatsbyjs.org#247]
Occasionally (as seen in #152 ) users are redirected to
https://gatsby-swag.myshopify.com
https://gatsbyjs.myshopify.com/
To get users back to https://store.gatsbyjs.org/ we should write a javascript function in the Shopify theme to get users back to where they need to be. Ideally they are never directed to the Shopify links, but I know it will occasionally happen. 

Also i know the cost is minimal but due to the fact that Gatsby is just using API why don't we switch to the lite plan? https://www.shopify.com/lite

**Comment by jlengstorf** [comment]
@isaac-martin do you mean dropping in a `window.location.href = 'https://store.gatsbyjs.org/'` in the template?

That could definitely make sense. There's a use case that we're considering where we have non-public items (such as bulk orders for events) in that Shopify store, which is password-protected, so while for our current use case that would be a good solution (as would switching to the lite plan — I think; it's hard to get a good comparison of what lite removes), there are some internal uses that require us to keep this functional.

Thanks so much for digging into this, though!

**Comment by isaac-martin** [comment]
Yeah exactly that @jlengstorf - all good If there is other use cases that you need the full functionality
