### ISSUE TITLE
Size Chart - The S size for Unisex seems to have a typo

### ISSUE THREAD

**Issue by harshil1712** [gatsbyjs/store.gatsbyjs.org#256]
Hey, I was just checking the size chart and found some typo. I am not sure if it's a really a typo. In the small size for the unisex chest, it says 36-36, shouldn't it be 36-38? The same issue is there for the measurements in  cm. If it's a typo I would like to help fix it.

**Comment by jlengstorf** [comment]
@harshil1712 yep, that's definitely a typo. We'd love to get a PR to fix that, thanks!

**Comment by harshil1712** [comment]
@jlengstorf fixed the typo.
