### ISSUE TITLE
Update error codes and discount code functionality

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#26]
* I wasn't able to apply the discount code "Your cart does not meet the requirements for the discount code". The error doesn't tell me what's wrong with my cart.

* Got a "Customer information does not meet the requirements for the discount code" message. Is that because I've used it already? This message could be clearer. If I've already used the discount code, then the store shouldn't generate new codes when I ask for them.

**Comment by jlengstorf** [comment]
I can't find any way to update Shopify error messages, so I'm not sure there's much I can do here.
