### ISSUE TITLE
Discount Code revoked during checkout process (while accepted at the start of it)

### ISSUE THREAD

**Issue by polarathene** [gatsbyjs/store.gatsbyjs.org#261]
## Summary

I unlocked the Level 2 swag code, it was accepted when applied at the first step of checkout process, but then stated it was not available for me to use after proceeding to the next step.

What happened? This error/notification is not clear why it's not available to me.

## Details

I tried to use the swag store today to get a Level 2 item. The discount code initially worked on the first screen of the checkout process, but after continuing to the next step, I was presented with an error that prevented the discount code from being usable.

> HOLYBUCKETS discount code isn’t available to you right now

I have tried dismissing the notification and adding it again but it's always the throwing the error now(going back to the 1st step of the checkout also displays the error so it's not specific to that). I can confirm the coupon is still on the sidebar and I've not used it before.

I did provide an e-mail at checkout different to the one auto-filled upon login in the sidebar(suggesting opt-in subscription to updates). The e-mail I provided at check-in is not the one tied to my Github account(but since I logged in via Github login I imagine that's a non-issue?)

---

Is it possible that the store thinks I've already used the coupon? I did use the Level 1 swag code, which should no longer be displayed as available afaik? **So the sidebar might not be communicating what the store believes is actually used?**

Or could it be due to my provided address? Is some of the swag restricted to where it can be delivered? The error isn't very clear on why it happened, just that something *potentially* went wrong.

## Some screenshots of what I see

![holybuckets_error](https://user-images.githubusercontent.com/5098581/55380060-860f5180-557b-11e9-8919-bc4648bc91a7.png)

![sidebar_coupons](https://user-images.githubusercontent.com/5098581/55380062-860f5180-557b-11e9-83e8-5d32489de7a8.png)

**Comment by polarathene** [comment]
Resolved. Changing the delivery contact e-mail to the one assigned to my Github account reapplied the swag code, it's now claimed and order completed.

Closing this as cause is now known. I have #262 open to deal with addressing the lack of clarity.

**Comment by ganapativs** [comment]
<img width="440" alt="Screenshot 2019-09-09 at 11 11 44 am" src="https://user-images.githubusercontent.com/4010960/64505816-ce812700-d2f2-11e9-9581-02e1bdce2f65.png">

I gave different email(not the primary email in GitHub) to gatsby store while logging in. Now coupon code "BUILDWITHGATSBY" won't work anymore when using either of the emails while check out 😅

@jlengstorf Help? 😬
