### ISSUE TITLE
Allow gifting of gatsby credits

### ISSUE THREAD

**Issue by a-trost** [gatsbyjs/store.gatsbyjs.org#268]
It would be great if you could purchase credits for other people in the Gatsby community, probably in $5 increments. Giving them out for contests or as a thank you for help seems like a great use of the swag store.

**Comment by jlengstorf** [comment]
Oh, that's a cool idea. It looks like this is possible — I just need to figure out some copy and make them available.

Thanks for this idea! cc @lindaleebumblebee
