### ISSUE TITLE
Can we change the title of the Gatsby Store?

### ISSUE THREAD

**Issue by KartSriv** [gatsbyjs/store.gatsbyjs.org#269]
What do you guys think about the title `Holy buckets! Get your Gatsby swag here!`? Should we change it? Please leave your comments below.
```
module.exports = {
  siteMetadata: {
    siteUrl: 'https://store.gatsbyjs.org',
    title: 'Holy buckets! Get your Gatsby swag here!',
    description:
      'Do you like spaced-out socks? All purple everything? Hitting #maximumcomf with JAMstack Jammies? Oh boy have we got the swag store for you!'
```

**Comment by KartSriv** [comment]
@jlengstorf

**Comment by jlengstorf** [comment]
Hey, @KartSriv! A quick question: do you have a reason for why you want to change the title, or what you'd like to change it to?

**Comment by Jared-Dev** [comment]
I'm personally a fan of the "Swag" moniker! Beyond that, I'm personally indifferent to the other copy!

**Comment by jlengstorf** [comment]
I'm happy to revisit this if there's a suggested new title, but for now I'm going to close.
