### ISSUE TITLE
Is it possible to redirect from the Shopify store to the Gatsby store?

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#27]
Technically, https://gatsby-swag.myshopify.com/ is visitable (though it _should_ be password-protected). Look into whether or not we can redirect that to store.gatsbyjs.org

**Comment by marisamorby** [comment]
When I try to visit the site from an incognito window it doesn't let me enter. I think if you have admin rights to the Shopify you'll be able to see it though.

![Screenshot 2018-06-29 16.01.13.png](https://images.zenhubusercontent.com/5b10124df58c642fb89c9de1/b4a2d860-b176-46a4-81d0-04854b1ccebb)
