### ISSUE TITLE
Consider adding a few relevant redirects

### ISSUE THREAD

**Issue by Jared-Dev** [gatsbyjs/store.gatsbyjs.org#273]
For whatever reason, I can never remember if it is `swag.gatsbyjs.org` or `store.gatsbyjs.org`. It might be a nice little assist to the users if there were some redirects in place to send a user to the correct domain.

Another possibility for redirects would be to add them for the `.com` site as well.

**Comment by Jared-Dev** [comment]
Seems like @kkemple mentioned something similar in #108

**Comment by jlengstorf** [comment]
Yeah, it seems like it's worth doing. I went ahead and set those up for .org and .com.
