### ISSUE TITLE
[feature] Copy button next to Level 1/2 swag code

### ISSUE THREAD

**Issue by anubhavsrivastava** [gatsbyjs/store.gatsbyjs.org#275]
Since the purpose of swag code is to copy and paste it at later stage (during checkout), it would be better to provide copy (to clipboard) functionality for codes.

**Comment by NeverMendel** [comment]
As far as I know, the discount code is applied automatically, so there is no need to copy and paste it manually.

**Comment by anubhavsrivastava** [comment]
> As far as I know, the discount code is applied automatically, so there is no need to copy and paste it manually.

Yes, that makes a better flow. But it didn't work for me, I had to paste it. Not sure why that happened

**Comment by jlengstorf** [comment]
The discount code isn't applied automatically. A copy button would be cool! I don't have the bandwidth to implement this, but a PR is welcome!
