### ISSUE TITLE
Typo Error in Dark Monogram Hoodie detail.

### ISSUE THREAD

**Issue by wit03** [gatsbyjs/store.gatsbyjs.org#278]
I found a typo error in this page and already tried to fix it. But I just realized that the item's detail was typed in Shopify

https://store.gatsbyjs.org/product/dark-monogram-hoodie

The word "ring spun" should be "ringspun" 

<img width="899" alt="Screen Shot 2562-06-25 at 07 29 51" src="https://user-images.githubusercontent.com/40893632/60060959-3f199e00-971d-11e9-96ce-00967171a5ff.png">

**Comment by kUSHAL0601** [comment]
Can I work on this ?

**Comment by wit03** [comment]
@kUSHAL0601 Sure!

**Comment by jlengstorf** [comment]
This change had to be made in Shopify — I just made it. Thanks for pointing this out!
