### ISSUE TITLE
Multiple variations?

### ISSUE THREAD

**Issue by MinxiesDev** [gatsbyjs/store.gatsbyjs.org#282]
Firstly, absolutely love this project. It's my main reason for using Shopify over other e-commerce solutions.

Does this set-up currently support multiple product variations?

Thanks for providing such a great project.

**Comment by jlengstorf** [comment]
@MinxiesDev there's variant support in the store, but we haven't done too much with the logic — we opted to try and keep this as simple as possible. However, the raw pieces are available; you should have access to the full output of the Shopify GraphQL API.

Good luck!

**Comment by MinxiesDev** [comment]
Great, thanks so much for the heads up!

Best, James
