### ISSUE TITLE
Remove apparel links for non-apparel items on the store

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/store.gatsbyjs.org#286]
## Description

For instance, the Diversity and Inclusion Donation item is not a piece of clothing, but has the "materials and fit" and "care instructions" links on the page

Page: https://store.gatsbyjs.org/product/diversity-inclusion-donation

## Preview

![Diversity and Inclusion page with apparel links on it](https://user-images.githubusercontent.com/3685876/65882262-b8e7a600-e362-11e9-81a3-d241ba5f8f97.png)

**Comment by codetronaut** [comment]
Please assign this issue to me.

**Comment by BALAJIRAO676** [comment]
Are you still working on this issue . If not i would be interested to take this up

**Comment by codetronaut** [comment]
yes @BALAJIRAO676 i'm working on it.

**Comment by greenorb007** [comment]
@lannonbr please help i am little new to this, i have researched the whole repo and found that there is a need for condition in this file "https://github.com/gatsbyjs/store.gatsbyjs.org/blob/master/src/components/ProductDetails/ProductDetails.js" in the return for the bifiguration of theproducts.

**Comment by codetronaut** [comment]
@lannonbr please help I am a little new to this, I have researched the whole repo and found that there is a need for the condition in this file "https://github.com/gatsbyjs/store.gatsbyjs.org/blob/master/src/components/ProductDetails/ProductDetails.js" in return for the bifiguration of the products.
