### ISSUE TITLE
Question: Do changes in shopify product trigger rebuilds?

### ISSUE THREAD

**Issue by jaredpalmer** [gatsbyjs/store.gatsbyjs.org#3]
on mobile, so don't have ability to dig into code, but just curious.

Also, if not, how would you do this?

**Comment by jlengstorf** [comment]
@jaredpalmer at the moment, no, but it's possible by setting up a webhook: [Shopify fires a webhook](https://help.shopify.com/api/reference/events/webhook) when products are updated, and [Netlify can trigger rebuilds via webhook](https://www.netlify.com/docs/webhooks/). I've created #4 to track implementing this.

(Unrelated: I saw you made an order. Thank you! We're still waiting for the swag to finish printing, so it'll be delayed in shipping. Sorry about that — I didn't realize the store would accept payments yet. 😅)
