### ISSUE TITLE
Error loading discount code

### ISSUE THREAD

**Issue by kimberrypi** [gatsbyjs/store.gatsbyjs.org#305]
I was trying to retrieve my coupon code from the Gatsby store and it returned this error. 

<img width="377" alt="Screen Shot 2019-10-14 at 4 26 43 PM" src="https://user-images.githubusercontent.com/20434382/66744190-618f1d00-eeae-11e9-8079-008349d652ce.png">

**Comment by kimberrypi** [comment]
Apparently this happens when you change your Github username. 
It worked after I used another email.

**Comment by muescha** [comment]
maybe adding some info about changed emails or that github email should match?
