### ISSUE TITLE
<img> tag is self closing

### ISSUE THREAD

**Issue by JohJohan** [gatsbyjs/store.gatsbyjs.org#307]
The image tag is self closing see as it cannot have child nodes.

More info see:
https://stackoverflow.com/questions/23890716/why-is-the-img-tag-not-closed-in-html/23890817

**Comment by JohJohan** [comment]
See https://github.com/gatsbyjs/store.gatsbyjs.org/pull/308

**Comment by sidharthachatterjee** [comment]
JSX requires us to close the tag as far as I can tell. Let's close this for now.
