### ISSUE TITLE
Care instructions and other copy doesn't show on page

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#31]
I've put in the care instructions and other information on the product information section, but since there is no product details page, the information doesn't show up.

![Screenshot 2018-06-21 09.07.54.png](https://images.zenhubusercontent.com/5b10124df58c642fb89c9de1/d9a6a276-ec69-4236-a54f-25124ec835cf)

**Comment by jlengstorf** [comment]
I think we need @fk's help with this. If I include the care instructions, the design gets pretty gross.

**Comment by jlengstorf** [comment]
This was closed by #64
