### ISSUE TITLE
Does not check against a null set value when retrieved from local storage (null !== 'null')

### ISSUE THREAD

**Issue by allelos** [gatsbyjs/store.gatsbyjs.org#312]
https://github.com/gatsbyjs/store.gatsbyjs.org/blob/b2f186f50384f7466687f253cd2cb760e29ce783/src/components/Layout/Layout.js#L219

It should be `if (existingCheckoutID && existingCheckoutID !== 'null')`

**Comment by Developerayo** [comment]
Oh, Thanks! @allelos can you open a PR for this?
