### ISSUE TITLE
store.gatsbyjs.org needs permission to access api.gatsby.org

### ISSUE THREAD

**Issue by webinista** [gatsbyjs/store.gatsbyjs.org#315]
I tried to claim my swag coupon, but the network request fails. Looks like it's a cross-origin issue. 

The console says:

```
Access to fetch at 'https://api.gatsbyjs.org/graphql' from origin 'https://store.gatsbyjs.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by jamo** [comment]
`curl -i https://api.gatsbyjs.org/graphql -XOPTIONS` seems to return `access-control-allow-origin: *`

**Comment by webinista** [comment]
This seems to be resolved now. Perhaps it was a temporary glitch. Going to close it.
