### ISSUE TITLE
Cannot start the project

### ISSUE THREAD

**Issue by marquez138** [gatsbyjs/store.gatsbyjs.org#326]
Hi im getting a graphql error when i run yarn start/gatsby develop. I yarn installed and builds successfully but get this error 
![screencapture-localhost-8000-2020-03-02-08_53_56](https://user-images.githubusercontent.com/6958145/75707812-af40d200-5c63-11ea-9703-f8fae5b225e1.png)

Any help would be appreciated

**Comment by qubis741** [comment]
update dependencies:
gatsby-source-shopify
shopify-buy
