### ISSUE TITLE
swags

### ISSUE THREAD

**Issue by mhmdrameez** [gatsbyjs/store.gatsbyjs.org#349]
Add 
Hoodies
Stickers for laptops
Cool Tshirt

**Comment by 9rstpn** [comment]
Laptop stickers 
cool t-shirts
printed socks
amazing hoodie 
#349

**Comment by 9rstpn** [comment]
Laptop stickers 
cool t-shirts
printed socks
amazing hoodie 
#224

**Comment by snehaljos** [comment]
good

**Comment by BlushBoy2611** [comment]
High capacity power banks
Face Masks
Anti Glare Glasses
Head and Hand bands
Cleaning microfiber clothes
Zippered sleeves for computer cables
Gaming chair
Dusting glove
..... and many more..

**Comment by LekoArts** [comment]
Please use https://github.com/gatsbyjs/store.gatsbyjs.org/issues/224
