### ISSUE TITLE
Explain the sentence ' not quite swags ....'

### ISSUE THREAD

**Issue by Trombokendu-dev** [gatsbyjs/store.gatsbyjs.org#350]
Kindly explain the sentence 'not quite swags ...' 
Also try to be short.

**Comment by fk** [comment]
👋 Hey @Trombokendu-dev!

I'll close this issue for now because I'm not sure what this is about. :/

I've searched the repository for `not quite` and `not quite swags` 🤷 — no luck.
Feel free add more context and reopen this issue!
