### ISSUE TITLE
Add FAQ for discount codes

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#36]
The discount codes have rules, and I don't think I can update Shopify's messaging, so we need an FAQ that explains how this works.

- Why isn't the discount code working?
    - Single user per contributor
    - Only valid for GitHub email
    - Only valid for certain swag
- How do I qualify for a contributor discount code?
- What about non-GitHub contributions?
    - What qualifies?
    - How do we verify non-GitHub contributions?

**Comment by fk** [comment]
Wondering where to put this information:

* We could display the FAQ in a modal similar to the "Size chart/caring information" modal.
* We could add a link to open this modal (or the "FAQ" page) next to the link opening the "Size chart/care instructions" modal.
* We could add a link in the footer that contains the legal information (also see #80).

**Comment by jlengstorf** [comment]
This should probably be a page/modal combo like the size/care info. See #89 for details on the pattern I think we should adopt for this.

I need to write this content. Wondering if we should add Markdown support, or if that's overkill. 😕

**Comment by jlengstorf** [comment]
@marisamorby should we add this to the README FAQ section as a short-term solution?

**Comment by marisamorby** [comment]
Closing this issue as a duplicate of Issue #94 Create Store FAQ in the README
