### ISSUE TITLE
Token Exposed

### ISSUE THREAD

**Issue by Corvettekez** [gatsbyjs/store.gatsbyjs.org#367]
Hello,

We found Open Environment Data :  ACCESS_TOKEN

Links:
https://github.com/gatsbyjs/store.gatsbyjs.org/blob/1e967796a5042363f5355a66eafb0b0d497ae67d/.env.development

https://github.com/gatsbyjs/store.gatsbyjs.org/blob/1e967796a5042363f5355a66eafb0b0d497ae67d/.env.production

![image](https://user-images.githubusercontent.com/77795516/105578499-8ee89d00-5d78-11eb-8ba6-2546c49f7c91.png)

If you found that as security bug, I would love to receive recognition 👍 
https://www.paypal.com/paypalme/Gihub

**Comment by LekoArts** [comment]
Those are public tokens ;)
