### ISSUE TITLE
Post your ideas for new swag Tshirt !

### ISSUE THREAD

**Issue by 786Nurjaman** [gatsbyjs/store.gatsbyjs.org#388]
Posters (was #99)
Sunglasses (was #105)
Knee-high socks (was #50)
Silk scrunchies with JAMstack Jammies pattern
Tie bar
Pocket square
Custom-printed Converse All-Stars
All-over printed hoodie and/or sweatshirt
Not quite swag, but cool things to do with the swag store:

Donate your rewards to charity (see #150 for one idea)
Limited-run swag collaborations with community designers (see #52)

**Comment by stewest** [comment]
"Captain Gatsby" Bobble Head
"Wonder Gatsby" Bobble Head
