### ISSUE TITLE
Bottle Swag

### ISSUE THREAD

**Issue by sijin-raj** [gatsbyjs/store.gatsbyjs.org#389]
i Win a Bottle from Gatsby ! But I saw the Price Bottle $500😱
##Comment your reaction
![Screen Shot 2021-07-08 at 12 08 00 PM](https://user-images.githubusercontent.com/54431616/125308967-fd351200-e34e-11eb-9b1a-58a6dbcb3439.png)

**Comment by internetburrito** [comment]
A fancy bottled indeed ;) In actuality, the price for winners is $0.00, which you can see where it says Total. So, why did we make a $500 bottle that you can get for free? Shopify requires a price for all items in our swag store, and to make sure that nobody purchased a bottle, and the bottle is only awarded to people who participate in the promo, we made it eye-poppingly expensive. Based on your reaction, success!
