### ISSUE TITLE
[Swag] Gatsby hoodies

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#40]
Because _of course_ we need hoodies!

**Comment by jlengstorf** [comment]
Hey, @lindaleebumblebee — here are some hoodie ideas!

![hoodie-gray](https://user-images.githubusercontent.com/163561/44480644-9ed48380-a5f8-11e8-9dd1-dfc28dd74ce3.jpg)
![hoodie-purple](https://user-images.githubusercontent.com/163561/44480649-a136dd80-a5f8-11e8-9af7-6da8b706b715.jpg)

**Comment by Dencraft** [comment]
Purple

**Comment by timroes** [comment]
How about the dark grey one with the logo position of the purple one - ideally the logo in purple?

**Comment by jakedohm** [comment]
Purple!

**Comment by justinwhall** [comment]
Grey! I'm ok with the purple T. Much more than that and I can't stop thinking...

![Purple People Eater](https://i.giphy.com/media/eXUWJVDocWJO/giphy.webp)

**Comment by starshaped** [comment]
I dig the purple 💜

**Comment by richbachman** [comment]
Purple!

**Comment by JonathanSpeek** [comment]
Grey color on the purple hoodie.

**Comment by saiprasad2595** [comment]
Purple is cute ❤️

**Comment by shobhitchittora** [comment]
Purple Hoodie. 💚💚

**Comment by virenb** [comment]
Purpleee

**Comment by lesliecdubs** [comment]
I'm going to break convention here and say grey! Love the logo treatment on that one, too.

**Comment by robotshateme** [comment]
Purple

**Comment by AlMon** [comment]
Grey

**Comment by jlengstorf** [comment]
Thanks, everyone!

The Twitter poll came back pretty close to 50/50, so we've decided we may as well do both. 😄 

![Why not both?](https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif)

We'll be ordering this shortly, and will make a ruckus when they're available in the [swag store](https://store.gatsbyjs.org/)!
