### ISSUE TITLE
Verify that Figma prototyping works across devices

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#42]
@jlengstorf 

We want to make sure that we're able to do lo-fi prototyping on multiple devices (laptop, iPad, mobile phone) using Figma. Please confirm that the prototypes will work on those devices

**Comment by jlengstorf** [comment]
@marisamorby @fk Give this link a shot on your various devices:

https://www.figma.com/proto/MkzcVh715IET8qptsUbuRQZN/Gatsby-Team-Photos?scaling=min-zoom&node-id=4%3A0

**Comment by jlengstorf** [comment]
Verified working on my Pixel 2 XL.

**Comment by fk** [comment]
👍  Working, and artboard gets scaled down to the width of the device (the latter doesn't matter much, we still need at least a prototype for mobile and one for tablet/desktop and up).
