### ISSUE TITLE
Due Date: 7/3 | Make profile updates on swag store

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#44]
@jlengstorf @fk 

## Goal
Make the profile area on the Swag Store dashboard easy to understand and fit in with upcoming design system.

## Problem
Currently, we don’t have a way for people to see an actual profile. 

## Potential Solutions
* add a dropdown next to the profile picture to show that people can use the dashboard?
* remove the profile area altogether so people don't get confused?

**Comment by fk** [comment]
First shot at profile—mobile only for now: https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=143%3A995&scaling=min-zoom

* decided to not do "pills" for GitHub issue labels as they require more space
* tried various hover states, but quite undecided still…I had better days 😁; FWIW I kinda like the orange background hover state for GitHub issue labels as it's a bit friendlier to the label icon
* not too happy with the coupon code either ;-) — it's OK, but nothing more than that

<img width="320" alt="logged in iphone se" src="https://user-images.githubusercontent.com/21834/42384502-6f080948-813a-11e8-8103-fb2bcc75c067.png">

<img width="320" alt="logged in iphone se 2" src="https://user-images.githubusercontent.com/21834/42385655-aa1eb47a-813d-11e8-8a7e-9e3ee7343cb6.png">

**Comment by fk** [comment]
In last Friday's meeting with @marisamorby and @jlengstorf we identified that we still need to work on

* improving the "discount code" "card": We want to try adding a couple of stars/sparkles or the "Gatsby Atom" 
![image](https://user-images.githubusercontent.com/21834/42460519-5e06addc-839e-11e8-8d31-f7306ad530f0.png) to the background of the card.
* ensuring that both discount code and "Issues we could use your help with" are clearly emphasized

**Comment by fk** [comment]
I'll provide an updated design for the "discount code" card later today.

**Comment by jlengstorf** [comment]
The majority of this is done, so I've opened #85 to track remaining work and will close this one.
