### ISSUE TITLE
Due 7/3: Review design decisions for Gatsby store that will influence and be part of the Gatsby design system

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#47]
@fk 

cc @jlengstorf

**Goal**

Create a design system that works for the Gatsby dashboard and can be carried over to other elements of Gatsby.

**To Review**
* border radius
* key lines
* outlines
* typography

**Comment by fk** [comment]
I started reviewing while putting together the first designs and prototypes, and expanded the list from the issue description and added my initial thoughts (and one question) below:

* **border radius:** I'd plead for sticking to what we've currently got for .org—two border radi sizes, defaulting to 2px to give all kinds of things—buttons, images, form elements—subtle rounded corners; 4px for larger buttons.
* **key lines:** @marisamorby is this the white 2px border-bottom of the header?
* **outlines:** For now I'm using 1px borders and colors from [the .org palette](https://github.com/gatsbyjs/gatsby/blob/440f020a5b310fbbafa58d45b9a7954d00f5a28f/www/src/utils/colors.js#L60-L71) for button and form outlines. Also see "colors" below.
* **typography:** Not an easy one. http://www.carbondesignsystem.com/style/typography/overview is a great inspiration.
* **form elements:** For now my first design shots stick closely to the browser default properties—trying to say: I'm not trying to do anything in the ballpark of e.g. Google Material Design's "floating labels". I would like to look into what IBM does with Carbon though: http://www.carbondesignsystem.com/components/form/code.
  * button
  * input
  * select
  * checkbox
  * number input (with controls to in-/decrease the input value)
  * label
* **spacing:** I think http://www.carbondesignsystem.com/style/spacing is an excellent approach to solve the different needs of spacing for components and general layout. Lets copy that!
* **colors**: Again, http://www.carbondesignsystem.com/style/color/usage is a great blueprint to learn from. The .org palette already contains a "ui" subsection which I still need/want to adjust/expand in terms of [contrast ratios](http://www.carbondesignsystem.com/guidelines/accessibility/color#color-contrast).
* **brand logo + product name:** Gatsby monogram + product name as [minimum](https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?scaling=min-zoom&node-id=11%3A53), full Gatsby logo (monogram + wordmark) + product name when the [space allows it](https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=28%3A1&scaling=min-zoom).
* **user profile** with **avatar**
* **dropdown**
* **loading overlay**
* **modal** or **sheet**
* (product) **card**
* **button**
* **link**
* **callout** (note, warning, success)
* **iconography**
* **badge** (shopping cart count)
* **shadows** (or "layers and depth")
* **table** (sizing charts)

**Comment by jlengstorf** [comment]
>    - *border radius:* I'd plead for sticking to what we've currently got
>    for .org—two border radi sizes, defaulting to 2px to give all kinds of
>    things—buttons, images, form elements—subtle rounded corners; 4px for
>    larger buttons
>
> Perfect. I didn't create a global setting for this, so maybe we do that in
`utils/styles.js`?

I agree with 2px/4px here.

>
>    - *key lines:* @marisamorby <https://github.com/marisamorby> is this
>    the white 2px border-bottom of the header?
>
> Yep!

>
>    - *outlines:* For now I'm using 1px borders and colors from the .org
>    palette
>    <https://github.com/gatsbyjs/gatsby/blob/440f020a5b310fbbafa58d45b9a7954d00f5a28f/www/src/utils/colors.js#L60-L71>
>    for button and form outlines. Also see "colors" below.
>
> Awesome. I didn't do that, but I would love to unify them.

>
>    - *typography:* Not an easy one.
>    http://www.carbondesignsystem.com/style/typography/overview is a great
>    inspiration.
>
> I think what we've got now is pretty okay. I don't want to get bogged down
here unless you see a problem.

>
>    - *form elements:* For now my first design shots stick closely to the
>    browser default properties—trying to say: I'm not trying to do anything in
>    the ballpark of e.g. Google Material Design's "floating labels". I would
>    like to look into what IBM does with Carbon though:
>    http://www.carbondesignsystem.com/components/form/code.
>       - button
>       - input
>       - select
>       - checkbox
>       - number input (with controls to in-/decrease the input value)
>       - label
>
> Agreed that Carbon is a great model. We could figure out which elements we
use now and build something to start us off in the design system.

>
>    -
>       - *spacing:* I think http://www.carbondesignsystem.com/style/spacing
>    is an excellent approach to solve the different needs of spacing for
>    components and general layout. Lets copy that!
>
> 👍

>
>    - *colors*: Again, http://www.carbondesignsystem.com/style/color/usage
>    is a great blueprint to learn from. The .org palette already contains a
>    "ui" subsection which I still need/want to adjust/expand in terms of contrast
>    ratios
>    <http://www.carbondesignsystem.com/guidelines/accessibility/color#color-contrast>
>    .
>
> 👍

>
>    - *brand logo + product name:* Gatsby monogram + product name as
>    minimum
>    <https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?scaling=min-zoom&node-id=11%3A53>,
>    full Gatsby logo (monogram + wordmark) + product name when the space
>    allows it
>    <https://www.figma.com/proto/gc7Tibfw1XuJ92vQxyfhQ7gm/store.gatsbyjs.org?node-id=28%3A1&scaling=min-zoom>
>    .
>    - *user profile* with *avatar*
>    - *dropdown*
>    - *loading overlay*
>    - *modal* or *sheet*
>    - (product) *card*
>    - *button*
>    - *link*
>    - *callout* (note, warning, success)
>    - *iconography*
>    - *badge* (shopping cart count)
>    - *shadows* (or "layers and depth")
>    - *table* (sizing charts)
>
>
This all looks great, @fk! Let me know how I can help.

> --

*Jason Lengstorf*
Find me online: *Twitter <https://twitter.com/jlengstorf>* · GitHub
<https://github.com/jlengstorf> · *LinkedIn
<https://linkedin.com/in/jlengstorf/>*
Oversharing at *lengstorf.com <https://lengstorf.com/>*

**Comment by marisamorby** [comment]
@jlengstorf and @fk 

Thinking I should move this over either to an RFC or Google doc (Google doc is better for commenting collaboration) so that this can be an ongoing. Is everyone okay with it being moved, and which method (RFC or Google Doc) do you prefer?

**Comment by jlengstorf** [comment]
Tagging @calcsam and @kkemple for opinions on this. Ultimately the design system is going to live in Storybook, right? How should we track/evolve it in the meantime?

**Comment by jlengstorf** [comment]
This hasn't moved, and we haven't been sharing components, so I'm going to close this for now. I'd very much like to see a design system come together, but the issue to track it should probably live somewhere else.
