### ISSUE TITLE
[Swag] Freelance Pants

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#51]
@marisamorby originally created this issue; moving it to the store repo.

Purple pajama pants with the Gatsby logo on them. 

Similar to this:

![Screenshot 2018-06-28 22.53.57.png](https://images.zenhubusercontent.com/5b10124df58c642fb89c9de1/8a5ecc73-f315-474d-bbe2-863932da1349)

**Comment by jlengstorf** [comment]
The order for these is underway! Final designs posted below.

On a personal note, I'd like everyone to know that making custom pajama pants is pretty much the pinnacle of my career. Bury me in JAMstack Jammies.

## JAMstack Jammies

<img width="1156" alt="screen shot 2018-09-05 at 4 34 25 pm" src="https://user-images.githubusercontent.com/163561/45126720-9d8f7480-b129-11e8-815c-2135e83aae23.png">

## Freelance Pants

<img width="1475" alt="screen shot 2018-09-05 at 4 35 09 pm" src="https://user-images.githubusercontent.com/163561/45126733-b3049e80-b129-11e8-96cf-ab21401d2723.png">

**Comment by garetmckinley** [comment]
I love these! I think it could also be cool to get a Louis Vuitton pattern with the gatsby logo in it in case you wanna feel boujee, but I don't have any clever names for it.

![image](https://user-images.githubusercontent.com/1624279/45331456-660d3780-b530-11e8-9080-f1fd9957f708.png)

**Comment by mrhut10** [comment]
Nice I need some of them!!!!

**Comment by lannonbr** [comment]
Closing this since the pants are now in the store
