### ISSUE TITLE
IDEA: Swag for charity collaborations

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#52]
What if we teamed up with different designers and artists to come up with swag, then held limited-time charity sales where all proceeds went to a charity of the designer's choice? (We'd vet all charities to make sure we know where we're sending donations.)

This could be a good idea for several reasons:

1. We get to contribute to good causes, and that's awesome
2. It gives us an opportunity to reach out to designers in the community for collaboration
3. Collab expands our network to groups we might not currently be reaching
4. When it's time to hire new contractors for design, we'll have prior experience with multiple designers to give us a head start
5. We get amazing swag for the store

I have several designers I know personally that we could reach out to, plus many in my Twitter network that I don't know personally, but could contact to gauge interest. I imagine we all know great designers, so this could be a fun way to tap our networks, do some good for the world, and stock up our swag store.

**Comment by marisamorby** [comment]
STEM group: http://www.stemforher.org/

**Comment by jlengstorf** [comment]
Superseded by #224

**Comment by SanchitMisal** [comment]
Good dashing hoodie or a pen drive
