### ISSUE TITLE
Make sure logo works in Shopify emails

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/store.gatsbyjs.org#53]
Right now the logo is breaking when test email is sent (Chrome, MacBook Pro, Gmail)

**Comment by varunzxzx** [comment]
Not only the test emails, the normal one is also breaking.

**Comment by jlengstorf** [comment]
Hey, @varunzxzx — which email are you talking about? Do you have a screenshot available?

**Comment by marisamorby** [comment]
Updated the logo and the emails should now work with the logo.

Screenshot below:

<img width="771" alt="screenshot 2018-06-30 15 32 19" src="https://user-images.githubusercontent.com/13393126/42129499-cd4c8912-7c7a-11e8-8323-97d139f1cc7e.png">
