### ISSUE TITLE
How to change to Passport?

### ISSUE THREAD

**Issue by sedubois** [gatsbyjs/store.gatsbyjs.org#67]
This is super cool. I would love to see how to switch to Passport.js instead of Auth0. Auth0 is quite expensive above 5000 users, and why pay if Passport.js offers what's needed for a simple authentication flow?

We currently have a Rails app where we pay nothing for user authentication, so I don't really see why we would switch to Auth0.

For the rest, this web app looks pretty much like what we wish to migrate towards, so I'd be super excited to see a sustainable authentication solution.

**Comment by jlengstorf** [comment]
Hi, @sedubois! I originally planned to use passport for this, but ran into challenges with passing JWT tokens between the store client and our back-end server. I want to dig into this later, but for now I don't have a ready answer for how you would do that. 

(If you tackle this, I'd be happy to help you write a tutorial on how to do it!)

I'm going to close this for now, but stay tuned for updates on this in the future.
