### ISSUE TITLE
Update product component

### ISSUE THREAD

**Issue by fk** [gatsbyjs/store.gatsbyjs.org#77]
* [x] thumbnail button style
* [x] `<select>` styles
* [x] headline and price styles

![image](https://user-images.githubusercontent.com/21834/42459098-729db414-839b-11e8-8917-4c34a22144b3.png)

**Comment by fk** [comment]
@jlengstorf Are you OK with visually hiding the `<select>` and <`input type="number">` labels (while making sure they're still accessible for screen readers)?

**Comment by jlengstorf** [comment]
I think that should be fine, as long as it's accessible.
