### ISSUE TITLE
Add legal info

### ISSUE THREAD

**Issue by fk** [gatsbyjs/store.gatsbyjs.org#80]
As I understand we currently only have a placeholder for this content:

![image](https://user-images.githubusercontent.com/21834/42459702-85f18918-839c-11e8-98c1-13b7060659a0.png)

I'm wondering how that information will look like and if we need to add pages (and a design) for this content.

/cc @marisamorby @jlengstorf

**Comment by jlengstorf** [comment]
Here's what I think we need:

- GDPR disclosure page explaining how we use information (e.g. Shopify customer creation, checking GitHub history, adding to our mailing list if you opt in).
    - @marisamorby do we need this? We don't store any data (that's all handled by GitHub/Shopify/MailChimp/Auth0).
- link to the GitHub repo for the store
- (once it's published) a link to the tutorial for building e-commerce sites with this stack

Anyone have other things we should include?

**Comment by jlengstorf** [comment]
Closed by #86
