### ISSUE TITLE
GitHub issue label links in dashboard point to `api.github.com/repos/gatsbyjs/gatsby/labels/…`

### ISSUE THREAD

**Issue by fk** [gatsbyjs/store.gatsbyjs.org#82]
![image](https://user-images.githubusercontent.com/21834/42565891-090cf044-8505-11e8-90d3-1f4c20c8ab07.png)

**Comment by fk** [comment]
Hm, not seeing this anymore…whatever happened when I took that screenshot. 🤷‍♂️ 😆

**Comment by colbyfayock** [comment]
@fk I'm seeing the same thing on https://store.gatsbyjs.org/account/dashboard

https://api.github.com/repos/gatsbyjs/gatsby/labels/%F0%9F%93%8D%20status:%20help%20wanted

![image](https://user-images.githubusercontent.com/1045274/43494579-88589536-9501-11e8-97ee-b7add2dc3f5d.png)
