### ISSUE TITLE
Add "Futura PT" webfont

### ISSUE THREAD

**Issue by fk** [gatsbyjs/store.gatsbyjs.org#84]
Currently Futura PT as referenced in https://github.com/gatsbyjs/store.gatsbyjs.org/blob/7708ffdfa7a1b805aa5cf7d2257067a5b2c22977/src/utils/styles.js#L65 is only seen by people who have the font installed locally.

We got a license for gatsbyjs.org, and we're using it for next.gatsbyjs.org, so I assume using it on another subdomain should be fine.

**Comment by jlengstorf** [comment]
Yep, same domain should be fine as far as I can understand the license text.
