### ISSUE TITLE
Update discount code display component

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/store.gatsbyjs.org#85]
This is a child issue of #44 so we track only the remaining work.

<img width="643" alt="screen shot 2018-07-12 at 10 27 30 am" src="https://user-images.githubusercontent.com/163561/42649312-3adad8a2-85be-11e8-9830-8d55d0ba81e3.png">

We want to improve the discount code display with a background image or something else to make it look more stylish. @fk has great ideas here, so we’ll let him run with it. 😄

**Comment by fk** [comment]
<img width="660" alt="bildschirmfoto 2018-07-18 um 16 54 01" src="https://user-images.githubusercontent.com/21834/42889639-362556f6-8aab-11e8-87ca-922b980cb435.png">

**Comment by jlengstorf** [comment]
![amazing](https://media.giphy.com/media/3o72F7YT6s0EMFI0Za/giphy.gif)

I love this.
