### ISSUE TITLE
localStorage for access tokens from Auth0

### ISSUE THREAD

**Issue by lukeocodes** [gatsbyjs/store.gatsbyjs.org#93]
Hey guys, since I developed the Gatsby guide I've been updating it and the React guidance/quickstarts to remove the use of localStorage. The fear is that XSS attacks can potentially be used to farm access tokens out of localStorage. 

Persistent token based authentication between browsing sessions can be achieved by reusing the SSO session on the authorization server.

We have a method `checkSession` inside our `auth0-js` SDK that allows you to acquire a new token from Auth0 for a user who is already authenticated against Auth0 for your domain/app.

We have a recommended solution that I am currently applying to our React guidance, I'll try PR for you as well while I'm at it.

**Comment by jlengstorf** [comment]
Thanks, @lukeoliff!

**Comment by jedrichards** [comment]
@lukeoliff @jlengstorf I've since dug a little deeper into the docs and worked it out. I've tried to encapsulate the approach as a Gatsby plugin, which:

- Usest the hosted login page
- Uses `checkSession` and stores tokens in memory only
- Automatically adds the login redirectUri route
- Exposes the Auth0 state and some callbacks (login, logout etc) to the rest of the app via React.Context

I'm just using it locally at the moment. Do you think something like this would be worth publishing?

https://gist.github.com/jedrichards/fc95660377d1af25c341b1e824be76bf

**Comment by jlengstorf** [comment]
This looks great! We need to do the same for this store as well. Thanks for putting the work in.

I do think this would be valuable. I believe @lukeoliff has a post somewhere that talks about this, but I don't know where it is.

**Comment by jedrichards** [comment]
Finding the Silent Authentication docs was the ah-hah moment for me

https://auth0.com/docs/api-auth/tutorials/silent-authentication

**Comment by lukeoliff** [comment]
Further to the above, logging out becomes a simple task of forgetting the in-memory auth and clearing the flag. 

This means other applications using the same auth session at the provider don't also get logged out. Log out from the auth server is considered different to log out from the app.

https://auth0.com/docs/libraries/auth0js/v9#logout

**Comment by jedrichards** [comment]
@lukeoliff That's very helpful thanks.

**Comment by La-comadreja** [comment]
I can take a crack at this one.

**Comment by jlengstorf** [comment]
@La-comadreja please do! I'll be streaming with the Auth0 team to learn how to set this stuff up, so if you hit any walls (or want to join the chat and give hints when I get stuck 😅) we'll be live at 9 am Pacific this Thursday on https://twitch.tv/jlengstorf

Thank you!

**Comment by La-comadreja** [comment]
Thanks.  This might take me a few days to really look at because I have other things to do.  Also thanks for the heads-up about the channel.  That is cool!

**Comment by jlengstorf** [comment]
This was patched a while back — should have close this!
