### ISSUE TITLE
Discount Network Error

### ISSUE THREAD

**Issue by marcobiedermann** [gatsbyjs/store.gatsbyjs.org#95]
It seams like your API for the discount is not working at the moment:

There was an error loading your discount code.
Here’s what came back from the server:

```
Network Error
```

![image](https://user-images.githubusercontent.com/5244986/42905987-f84a6f22-8ad9-11e8-912f-744f6f0b6b9e.png)

**Comment by marcobiedermann** [comment]
Resolved in the meanwhile!

**Comment by jlengstorf** [comment]
Hmmm... @thebigredgeek maybe we should look at migrating to our own infra sooner rather than later.

**Comment by jlengstorf** [comment]
After discussion with the team, we're going to beef up our server to avoid downtime like this. Opening #97 to track this.

**Comment by marcobiedermann** [comment]
@jlengstorf Thanks for taking care of it
