### ISSUE TITLE
[Swag] Posters

### ISSUE THREAD

**Issue by thebigredgeek** [gatsbyjs/store.gatsbyjs.org#99]
I am planning on getting a Gatsby poster for my home office.  This might be an interesting piece of swag for the store, too.  Thoughts?

**Comment by jlengstorf** [comment]
I love this idea, @thebigredgeek — I guess it'll depend on who owns the rights to artwork and whether or not anyone in the community wants a brand poster. I haven't seen this before, but that doesn't mean no one would like it. 😄 

I've added this to the list of swag ideas so we review it when the next swag project gets prioritized.

**Comment by jlengstorf** [comment]
Superseded by #224

**Comment by SWAROOPBHAGWAT** [comment]
Poster is a great idea. Posters having motivational quotes and pictures can be considered as a swag. People would love it.

**Comment by YoussefAyou** [comment]
Gift card can be helpful
